### ISSUE TITLE
WSL1 And Cypress

### ISSUE THREAD

**Issue by glebme** [csesoc/csesoc.unsw.edu.au#85]
Since WSL1 does not officially support GUI applications (like Cypress), the easiest way to set Cypress up is by installing a Windows package manager (i.e. Scoop, Chocolatey) and installing `nodejs` and `yarn` through it.

Check with @abiramen to see if this is an issue on WSL2

**Comment by abiramen** [comment]
Will look into this:

https://nickymeuleman.netlify.app/blog/gui-on-wsl2-cypress
