### ISSUE TITLE
Prototype the front end

### ISSUE THREAD

**Issue by gawdn** [csesoc/csesoc.unsw.edu.au#9]
- [ ] [Interactive prototype](https://www.figma.com/files/team/722281823811653394/CSE)
- [ ] static pages
- [ ] sitemap
- [ ] links
- [ ] animations/interactions
- [ ] check diff screen sizes

**Comment by elizabethzhong** [comment]
[https://www.figma.com/file/Xoi2xxJ1RtU6FbNTV7OOSm75/Front-Page?node-id=0%3A1](url)
